import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

const Home: NextPage = (props) => {
  const worldHeight = 30
  const worldWidth = 30
  const [houseMap, setHouseMap] = useState(Array(worldHeight).fill(Array(worldWidth).fill(0)))
  const grassMap = Array(worldHeight).fill(Array(worldWidth).fill(1))
  const championMap = Array(worldHeight).fill(Array(worldWidth).fill(0))
  const barrackMap = Array(worldHeight).fill(Array(worldWidth).fill(0))
  const soldierMap = Array(worldHeight).fill(Array(worldWidth).fill(0))
  const towerMap = Array(worldHeight).fill(Array(worldWidth).fill(0))

  useEffect(() => {
    let ws = new WebSocket("ws://localhost:8000")
    ws.onopen = (event) => {
      ws.send(JSON.stringify({ type: "event", event: "connection", data: "some string or smth" }))
    }
    ws.onmessage = (message) => {
      let data = JSON.parse(message.data)
      for (let item of data.data) {
        houseMap[item.loc.row][item.loc.col] = 1
        console.log(houseMap)
      }

    }
  }, [])




  // const houseMap = Array.from({ length: worldHeight }, () => (Array.from({ length: worldWidth }, () => Math.floor(Math.random() * 2))))
  // const championMap = Array.from({ length: worldHeight }, () => (Array.from({ length: worldWidth }, () => Math.floor(Math.random() * 2))))
  // const barrackMap = Array.from({ length: worldHeight }, () => (Array.from({ length: worldWidth }, () => Math.floor(Math.random() * 2))))
  // const soldierMap = Array.from({ length: worldHeight }, () => (Array.from({ length: worldWidth }, () => Math.floor(Math.random() * 2))))
  // const towerMap = Array.from({ length: worldHeight }, () => (Array.from({ length: worldWidth }, () => Math.floor(Math.random() * 2))))

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        {houseMap.map((row: Array<number>, rowIndex: number) => (
          row.map((value: number, colIndex: number) => (
            value !== 0 && <House key={`${rowIndex}${colIndex}`} top={(rowIndex)} left={(colIndex)} />
          ))
        ))}
        {grassMap.map((row: Array<number>, rowIndex: number) => (
          row.map((value: number, colIndex: number) => (
            value !== 0 && <Tile key={`${rowIndex}${colIndex}`} top={(rowIndex)} left={(colIndex)} />
          ))
        ))}
        {championMap.map((row: Array<number>, rowIndex: number) => (
          row.map((value: number, colIndex: number) => (
            value !== 0 && <Champion key={`${rowIndex}${colIndex}`} top={(rowIndex)} left={(colIndex)} />
          ))
        ))}
        {barrackMap.map((row: Array<number>, rowIndex: number) => (
          row.map((value: number, colIndex: number) => (
            value !== 0 && <Barrack key={`${rowIndex}${colIndex}`} top={(rowIndex)} left={(colIndex)} />
          ))
        ))}
        {soldierMap.map((row: Array<number>, rowIndex: number) => (
          row.map((value: number, colIndex: number) => (
            value !== 0 && <Soldier key={`${rowIndex}${colIndex}`} top={(rowIndex)} left={(colIndex)} />
          ))
        ))}
        {towerMap.map((row: Array<number>, rowIndex: number) => (
          row.map((value: number, colIndex: number) => (
            value !== 0 && <Tower key={`${rowIndex}${colIndex}`} top={(rowIndex)} left={(colIndex)} />
          ))
        ))}
      </main>
    </>
  );
};

export default Home;

type TilePosition = {
  top: number;
  left: number;
};

const Tile = ({
  top,
  left,
}: TilePosition) => {
  return (<img src="grass.png" style={{ height: 96, width: 96, position: "absolute", left: 48 + left * 96, top: 48 + top * 96, zIndex: 0 }} />);
};

const House = ({
  top,
  left,
}: TilePosition) => {
  return (<img src="house.png" style={{ height: 48, width: 48, position: "absolute", left: 48 + left * 96, top: 48 + top * 96, marginLeft: 10, marginTop: 20, zIndex: 1 }} />);
};

const Champion = ({
  top,
  left,
}: TilePosition) => {
  return (<img src="champion.png" style={{ height: 48, width: 48, position: "absolute", left: 48 + left * 96, top: 48 + top * 96, marginLeft: 10, marginTop: 20, zIndex: 2 }} />);
};

const Barrack = ({
  top,
  left,
}: TilePosition) => {
  return (<img src="barrack.png" style={{ height: 48, width: 48, position: "absolute", left: 48 + left * 96, top: 48 + top * 96, marginLeft: 10, marginTop: 20, zIndex: 3 }} />);
};

const Soldier = ({
  top,
  left,
}: TilePosition) => {
  return (<img src="soldier.png" style={{ height: 48, width: 48, position: "absolute", left: 48 + left * 96, top: 48 + top * 96, marginLeft: 10, marginTop: 20, zIndex: 4 }} />);
};

const Tower = ({
  top,
  left,
}: TilePosition) => {
  return (<img src="tower.png" style={{ height: 48, width: 48, position: "absolute", left: 48 + left * 96, top: 48 + top * 96, marginLeft: 10, marginTop: 20, zIndex: 5 }} />);
};